### ISSUE TITLE
pmap_qto

### ISSUE THREAD

**Issue by ElianHugh** [ElianHugh/quartools#8]
As per @elipousson's suggestion, we should implement a `pmap_qto` method that would compliment the new `map_qto` method introduced in eli's PR.

TODO
- Grab the pmap standalone from purrr

**Comment by elipousson** [comment]
Hey @ElianHugh – I spotted a minor issue with the revisions to `map_qto()` completed along with the implementation of `pmap_qto()`. Both `qto_block()` and `qto_div()` provided `sep` and `collapse` parameters with no leading period. This meant that `map_qto()` *already* had support for passing those parameters to the supplied function and *separately* passing a .sep and .collapse parameter to the optional `qto_block()` call. With the changes to the function, they are both passed as the same value and you can't use separate values for the two different calls.

It may or may not matter from a practical standpoint but I thought it might be an unintended change and wanted to make sure you saw it.

**Comment by ElianHugh** [comment]
Hi @elipousson, thank you for noting that -- definitely something I overlooked. I'll revert that change and add a test for for the future.
